import { createContext, useContext, useState, useCallback, type ReactNode } from "react";

export type Language = "zh" | "en";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

const translations: Record<Language, Record<string, string>> = {
  zh: {
    // Navbar
    "nav.features": "功能特色",
    "nav.dating": "交友配對",
    "nav.campus": "校園工具",
    "nav.pricing": "定價方案",
    "nav.login": "登入",
    "nav.waitlist": "加入社群",

    // Hero
    "hero.badge": "僅限 .edu.hk 認證學生",
    "hero.title1": "你的校園。",
    "hero.title2": "你的聲音。",
    "hero.title3": "你的規則。",
    "hero.subtitle": "專為香港學生打造的認證匿名社群平台。自由分享、真實連結、在校園中茁壯成長——全部在一個受信任的封閉社群中。",
    "hero.cta.waitlist": "加入社群",
    "hero.cta.explore": "探索功能",
    "hero.stat.institutions": "認證院校",
    "hero.stat.users": "潛在用戶",
    "hero.stat.privacy": "隱私模式",

    // Institutions
    "institutions.subtitle": "支援全港超過 <accent>20+</accent> 間院校",

    // Verification
    "verification.badge": "信任架構",
    "verification.title1": "認證。匿名。",
    "verification.title2": "由你掌控。",
    "verification.subtitle": "註冊需要有效的 .edu.hk 電郵。無機器人、無網絡噴子，只有真實學生選擇展示多少身份。",
    "verification.ghost.name": "隱身模式",
    "verification.ghost.tag": "匿名",
    "verification.ghost.desc": "完全匿名。不透露任何身份。自由發言，不留痕跡。",
    "verification.campus.name": "校園模式",
    "verification.campus.tag": "HKU SPACE · ENFP",
    "verification.campus.desc": "顯示你的院校和 MBTI 類型。在不完全暴露身份的情況下增加個性背景。",
    "verification.major.name": "學科模式",
    "verification.major.tag": "PolyU · Nursing · ISFJ",
    "verification.major.desc": "顯示院校、學科和 MBTI。在學術討論中建立可信度。",

    // Features
    "features.badge": "社交與學術中心",
    "features.title1": "讓學生每天回來的",
    "features.title2": "日常鉤子",
    "features.subtitle": "高度本地化、貼近生活的內容，推動每日活躍使用。從轉學建議到校園八卦——全部經過認證，全部匿名。",
    "features.jupas.title": "Non-JUPAS 與銜接課程中心",
    "features.jupas.desc": "大專學生獲取轉學建議，大學生匿名分享成功的 GPA、面試問題和作品集技巧。為大專社群創造巨大的病毒式傳播循環。",
    "features.mbti.title": "MBTI 驅動辯論",
    "features.mbti.desc": "MBTI 融入每個校園和學科標籤。即時了解你辯論對手的「氛圍」——為校園八卦增添幽默和心理深度。",
    "features.missed.title": "錯過的緣分",
    "features.missed.desc": "超本地化的喊話，例如「給今天下午3點在 HKCC 圖書館戴黑色帽子的男生...」用戶可以認領帖子以開始匿名私聊。",
    "features.salary.title": "薪資與實習透明度",
    "features.salary.desc": "學長姐匿名分享實習薪資、面試經歷和有毒公司的警告。來自真實學生的真實數據。",

    // Dating
    "dating.badge": "慢揭示交友",
    "dating.title1": "個性優先。",
    "dating.title2": "外貌其後。",
    "dating.subtitle": "專為治癒滑動疲勞而設計。優先考慮共同的學術奮鬥和真實個性，而非單純的外貌。",
    "dating.step1.title": "氛圍檢測",
    "dating.step1.desc": "在匿名討論中有精彩交流？發送互相的「氛圍檢測」以開啟私聊。論壇互動變成真實連結。",
    "dating.step2.title": "模糊配對檔案",
    "dating.step2.desc": "創建一個包含 MBTI、3個興趣愛好、學科和高度模糊照片的交友檔案。個性優先，外貌其次。",
    "dating.step3.title": "20條訊息解鎖",
    "dating.step3.desc": "配對後只能看到 MBTI 和學科。隨著訊息交換，照片逐漸清晰。到第20條訊息——完全揭示。",
    "dating.step4.title": "組隊配對",
    "dating.step4.desc": "與1-2個朋友連結檔案，一起滑動其他小組。低壓力的群組聚會，例如「兩個 INTP 工程師找人一起打邊爐」。",

    // Campus Tools
    "campus.badge": "校園實用工具",
    "campus.title1": "讓校園生活",
    "campus.title2": "更輕鬆的工具",
    "campus.subtitle": "生存學期的必備工具。從課程評價到教科書交易——全在一個地方。",
    "campus.rate.title": "Rate-My-Course HK",
    "campus.rate.desc": "匿名、可搜索的課程和教授評價資料庫。在加退選期間流量將激增——終極學期生存工具。",
    "campus.market.title": "認證校園市集",
    "campus.market.desc": "買賣二手教科書、宿舍電器或轉租學生住房。.edu 認證將詐騙率降至接近零。",
    "campus.timetable.title": "時間表同步與自習夥伴",
    "campus.timetable.desc": "輸入你的課表，自動加入班級聊天室，並切換「尋找自習夥伴」狀態，僅對同班同學可見。",

    // Pricing
    "pricing.badge": "定價方案",
    "pricing.title1": "免費使用。",
    "pricing.title2": "Pro 制霸。",
    "pricing.subtitle": "UniVibe HK 對所有認證學生免費。只需 HK$18/月即可解鎖高級功能。",
    "pricing.free": "免費版",
    "pricing.free.price": "HK$0",
    "pricing.free.period": "/月",
    "pricing.free.cta": "免費開始",
    "pricing.free.f1": "匿名發帖，3種隱私模式",
    "pricing.free.f2": "Non-JUPAS 與銜接課程討論區",
    "pricing.free.f3": "錯過的緣分討論區",
    "pricing.free.f4": "Rate-My-Course HK 存取",
    "pricing.free.f5": "校園市集",
    "pricing.free.f6": "時間表同步與自習夥伴",
    "pricing.free.f7": "慢揭示交友配對",
    "pricing.pro": "Pro",
    "pricing.pro.price": "HK$18",
    "pricing.pro.period": "/月",
    "pricing.pro.popular": "熱門",
    "pricing.pro.cta": "升級至 Pro",
    "pricing.pro.f1": "包含免費版所有功能，另加：",
    "pricing.pro.f2": "查看誰瀏覽了你的交友檔案",
    "pricing.pro.f3": "按 MBTI 或學科篩選配對",
    "pricing.pro.f4": "置頂市集商品列表",
    "pricing.pro.f5": "每週1次直接「超級聊天」",
    "pricing.pro.f6": "優先客服支援",
    "pricing.b2b.title": "企業方案",
    "pricing.b2b.subtitle": "觸及香港最活躍的學生受眾。",
    "pricing.recruiter.title": "招聘席位",
    "pricing.recruiter.desc": "銀行、四大會計師事務所和科技公司發布認證的 MT/實習職位並舉辦匿名 AMA。",
    "pricing.recruiter.price": "由 HK$5,000/月起",
    "pricing.ads.title": "超本地化廣告",
    "pricing.ads.desc": "向特定校園的學生推廣你的業務。置頂帖子、橫幅廣告位等。",
    "pricing.ads.price": "自訂定價",

    // Tech
    "tech.badge": "技術架構",
    "tech.title1": "為",
    "tech.title2": "規模與安全而建",
    "tech.subtitle": "企業級安全和性能，由深諳信任至上的金融科技人才設計。",
    "tech.stack.title": "現代技術棧",
    "tech.stack.desc": "Next.js (React) 前端搭配 Node.js/PostgreSQL 後端，實現快速、類應用的性能和複雜的關聯數據處理。",
    "tech.ai.title": "AI 審核",
    "tech.ai.desc": "從第一天起整合 AI 審核 API，標記仇恨言論、霸凌和人肉搜索。安全是不可妥協的。",
    "tech.ban.title": "終極封禁大錘",
    "tech.ban.desc": "嚴重違規將導致永久 .edu.hk 哈希封禁。沒有新帳號，壞人沒有第二次機會。",
    "tech.infra.title": "可擴展基礎設施",
    "tech.infra.desc": "專為應對加退選期間和校園病毒式傳播時刻的流量高峰而建。支援 WebSocket 的即時聊天。",

    // CTA
    "cta.title1": "準備好加入",
    "cta.title2": "封閉花園",
    "cta.title3": "了嗎？",
    "cta.subtitle": "UniVibe HK 即將推出。成為首批認證學生，體驗香港一直在等待的校園超級應用。",
    "cta.waitlist": "加入社群",
    "cta.business": "企業合作洽詢",

    // Footer
    "footer.desc": "專為香港學生打造的認證匿名社群與校園超級應用。",
    "footer.product": "產品",
    "footer.company": "公司",
    "footer.legal": "法律",
    "footer.about": "關於我們",
    "footer.blog": "部落格",
    "footer.careers": "加入我們",
    "footer.press": "媒體報導",
    "footer.privacy": "隱私政策",
    "footer.terms": "服務條款",
    "footer.guidelines": "社群守則",
    "footer.copyright": "UniVibe HK. 保留所有權利。",
    "footer.tagline": "由香港學生打造，為香港學生服務。",

    // Common
    "common.coming_soon": "功能即將推出",

    // Login page
    "login.email.title": "加入你的校園社群",
    "login.email.subtitle": "輸入你的 .edu.hk 電郵地址開始驗證。",
    "login.email.cta": "發送驗證碼",
    "login.email.privacy_note": "我們只使用你的電郵進行身份驗證。你的電郵地址會被哈希處理，永遠不會被公開或分享給第三方。",
    "login.verify.title": "輸入驗證碼",
    "login.verify.subtitle": "我們已發送6位數驗證碼至",
    "login.verify.detected": "已偵測",
    "login.verify.cta": "驗證並加入",
    "login.verify.hint": "驗證碼已發送至你的電郵，10分鐘內有效",
    "login.success.title": "歡迎加入 UniVibe！",
    "login.success.subtitle": "你的身份已驗證。正在進入社群...",
    "login.success.redirect": "正在跳轉至動態牆...",
    "login.error.invalid_email": "請使用有效的 .edu.hk 電郵地址",
    "login.error.invalid_code": "請輸入完整的6位數驗證碼",
    "login.toast.code_sent": "驗證碼已發送！請檢查你的電郵",
    "login.toast.verified": "驗證成功！",

    // Feed page
    "feed.nav.feed": "動態",
    "feed.nav.dating": "交友",
    "feed.nav.tools": "工具",
    "feed.nav.profile": "個人",
    "feed.nav.logout": "登出",
    "feed.search": "搜尋帖子...",
    "feed.cat.all": "全部",
    "feed.cat.trending": "熱門",
    "feed.cat.missed": "錯過的緣分",
    "feed.cat.salary": "薪資透明",
    "feed.compose.title": "發布新帖子",
    "feed.compose.placeholder": "分享你的想法...",
    "feed.compose.submit": "發布",
    "feed.post.success": "帖子已發布！",
    "feed.privacy.ghost": "隱身",
    "feed.privacy.campus": "校園",
    "feed.privacy.major": "學科",

    // Dating page
    "dating.tab.discover": "探索",
    "dating.tab.matches": "配對",
    "dating.tab.profile": "交友檔案",
    "dating.discover.title": "探索配對",
    "dating.filter": "篩選",
    "dating.filter.sexuality": "性取向篩選",
    "dating.filter.all": "全部",
    "dating.match": "匹配",
    "dating.photo_clarity": "照片清晰度",
    "dating.messages_to_reveal": "條訊息後完全揭示",
    "dating.messages_short": "條訊息",
    "dating.clarity": "清晰度",
    "dating.skip": "跳過",
    "dating.vibe_check": "氛圍檢測",
    "dating.vibe_sent": "氛圍檢測已發送！等待對方回應 💫",
    "dating.matches.title": "你的配對",
    "dating.matches.empty": "還沒有配對。開始探索吧！",
    "dating.profile.title": "設定交友檔案",
    "dating.profile.sexuality": "性取向",
    "dating.profile.mbti": "你的 MBTI",
    "dating.profile.interests": "興趣愛好",
    "dating.profile.min": "最少",
    "dating.profile.save": "儲存檔案",
    "dating.profile.active": "✓ 你的交友檔案已啟用！其他用戶現在可以看到你。",
    "dating.error.mbti": "請選擇你的 MBTI 類型",
    "dating.error.interests": "請至少選擇3個興趣",
    "dating.profile_saved": "交友檔案已儲存！",
    "dating.discover.subtitle": "個性優先，外貌其後 ✨",
    "dating.filter.gender": "性別",
    "dating.filter.gender.all": "全部",
    "dating.filter.gender.male": "♂ 男",
    "dating.filter.gender.female": "♀ 女",
    "dating.filter.gender.nonbinary": "⚧ 非二元",
    "dating.filter.age": "年齡",
    "dating.filter.school": "院校",
    "dating.filter.faculty": "學院",
    "dating.filter.district": "地區",
    "dating.filter.relationship": "關係類型",
    "dating.filter.religion": "宗教",
    "dating.filter.clear": "清除所有篩選",
    "dating.back": "返回",
    "dating.msg_input": "輸入訊息...",
    "dating.msg_unlock": "訊息解鎖",
    "dating.unlocked": "已解鎖",
    "dating.reveal_desc": "配對後透過訊息逐步解鎖，20條訊息後完全揭示 🔓",
    "dating.no_more": "暫時冇更多配對",
    "dating.no_more_sub": "稍後再返嚟睇吓 💫",
    "dating.how_it_works": "慢揭示交友點樣運作？",
    "dating.how.vibe.title": "氛圍檢測",
    "dating.how.vibe.desc": "喺論壇有好嘅交流？發送氛圍檢測開始私聊",
    "dating.how.blur.title": "模糊照片",
    "dating.how.blur.desc": "一開始只見到 MBTI 同學科，照片係模糊嘅",
    "dating.how.msg.title": "20條訊息",
    "dating.how.msg.desc": "每發一條訊息，照片就會清晰少少",
    "dating.how.group.title": "組隊配對",
    "dating.how.group.desc": "同朋友一齊配對，低壓力嘅群組聚會",
    "dating.matches.subtitle": "繼續傾偈解鎖對方嘅照片 🔓",
    "dating.matches.no_matches": "仲未有配對",
    "dating.matches.go_discover": "去「探索」頁面發送氛圍檢測開始配對！",
    "dating.matches.start": "開始探索",
    "dating.profile.subtitle": "其他用戶會見到你嘅 MBTI、興趣同模糊照片",
    "dating.profile.selected": "已選",
    "dating.send_more": "再發",
    "dating.to_fully_unlock": "條訊息即可完全解鎖",
  },
  en: {
    // Navbar
    "nav.features": "Features",
    "nav.dating": "Dating",
    "nav.campus": "Campus Tools",
    "nav.pricing": "Pricing",
    "nav.login": "Log In",
    "nav.waitlist": "Join the Community",

    // Hero
    "hero.badge": "Verified .edu.hk Students Only",
    "hero.title1": "Your Campus.",
    "hero.title2": "Your Voice.",
    "hero.title3": "Your Rules.",
    "hero.subtitle": "The verified anonymous network for Hong Kong students. Share freely, connect authentically, and thrive on campus — all within a trusted, walled-garden community.",
    "hero.cta.waitlist": "Join the Community",
    "hero.cta.explore": "Explore Features",
    "hero.stat.institutions": "Verified Institutions",
    "hero.stat.users": "Potential Users",
    "hero.stat.privacy": "Privacy Modes",

    // Institutions
    "institutions.subtitle": "Supporting <accent>20+</accent> institutions across Hong Kong",

    // Verification
    "verification.badge": "Trust Architecture",
    "verification.title1": "Verified. Anonymous.",
    "verification.title2": "Yours.",
    "verification.subtitle": "Registration requires a valid .edu.hk email. No bots. No trolls. Just real students choosing how much to reveal.",
    "verification.ghost.name": "Ghost Mode",
    "verification.ghost.tag": "Anonymous",
    "verification.ghost.desc": "Fully anonymous. No identity revealed. Speak your mind freely without any trace.",
    "verification.campus.name": "Campus Mode",
    "verification.campus.tag": "HKU SPACE · ENFP",
    "verification.campus.desc": "Show your institution and MBTI type. Add personality context without full exposure.",
    "verification.major.name": "Major Mode",
    "verification.major.tag": "PolyU · Nursing · ISFJ",
    "verification.major.desc": "Display institution, major, and MBTI. Build credibility in academic discussions.",

    // Features
    "features.badge": "Social & Academic Hub",
    "features.title1": "The Daily Hook That Keeps",
    "features.title2": "Students Coming Back",
    "features.subtitle": "Highly localized, relatable content that drives daily active usage. From transfer advice to campus gossip — all verified, all anonymous.",
    "features.jupas.title": "Non-JUPAS & Articulation Hub",
    "features.jupas.desc": "Tertiary students get transfer advice while university students anonymously share successful GPAs, interview questions, and portfolio tips. A massive viral loop for the 大專 community.",
    "features.mbti.title": "MBTI-Powered Debates",
    "features.mbti.desc": "MBTI is baked into every Campus and Major tag. Instantly understand the vibe of who you're debating — adding humor and psychological depth to campus gossip.",
    "features.missed.title": "Missed Connections",
    "features.missed.desc": "Hyper-local shoutouts like \"To the guy in the black cap at HKCC library today at 3 PM...\" Users can claim posts to start anonymous private chats.",
    "features.salary.title": "Salary & Internship Transparency",
    "features.salary.desc": "Seniors anonymously share internship salaries, interview experiences, and warnings about toxic companies. Real data from real students.",

    // Dating
    "dating.badge": "Slow-Reveal Dating",
    "dating.title1": "Personality First.",
    "dating.title2": "Looks Later.",
    "dating.subtitle": "Designed to cure swiping fatigue. Prioritize shared academic struggles and genuine personality over appearance alone.",
    "dating.step1.title": "The Vibe Check",
    "dating.step1.desc": "Great exchange in an anonymous thread? Send a mutual \"Vibe Check\" to open a private chat. Forum interactions become real connections.",
    "dating.step2.title": "Blurred Match Profile",
    "dating.step2.desc": "Create a dating profile with your MBTI, 3 hobbies, major, and heavily blurred photos. Personality first, appearance second.",
    "dating.step3.title": "20-Message Unblur",
    "dating.step3.desc": "Chat with only MBTI and major visible. As you exchange messages, photos slowly come into focus. By message 20 — full reveal.",
    "dating.step4.title": "Group Swiping",
    "dating.step4.desc": "Link with 1-2 friends to swipe on other groups. Low-pressure hangouts like \"Two INTP engineers looking for hotpot partners.\"",

    // Campus Tools
    "campus.badge": "Campus Utility",
    "campus.title1": "Tools That Make Campus Life",
    "campus.title2": "Easier",
    "campus.subtitle": "Practically mandatory for surviving the semester. From course reviews to textbook trading — all in one place.",
    "campus.rate.title": "Rate-My-Course HK",
    "campus.rate.desc": "Anonymous, searchable database of course and professor reviews. Traffic spikes during add/drop periods — the ultimate semester survival tool.",
    "campus.market.title": "Verified Marketplace",
    "campus.market.desc": "Buy and sell used textbooks, dorm appliances, or sublet student housing. The .edu verification drops the scam rate to near zero.",
    "campus.timetable.title": "Timetable Sync & Study Buddy",
    "campus.timetable.desc": "Input your schedule, auto-join class chat rooms, and toggle a \"Looking for Study Buddy\" status visible only to classmates.",

    // Pricing
    "pricing.badge": "Pricing",
    "pricing.title1": "Free to Use.",
    "pricing.title2": "Pro to Dominate.",
    "pricing.subtitle": "UniVibe HK is free for all verified students. Unlock premium features for just HK$18/month.",
    "pricing.free": "Free",
    "pricing.free.price": "HK$0",
    "pricing.free.period": "/month",
    "pricing.free.cta": "Get Started Free",
    "pricing.free.f1": "Anonymous posting with 3 privacy modes",
    "pricing.free.f2": "Non-JUPAS & Articulation boards",
    "pricing.free.f3": "Missed Connections board",
    "pricing.free.f4": "Rate-My-Course HK access",
    "pricing.free.f5": "Campus Marketplace",
    "pricing.free.f6": "Timetable Sync & Study Buddy",
    "pricing.free.f7": "Slow-Reveal dating matches",
    "pricing.pro": "Pro",
    "pricing.pro.price": "HK$18",
    "pricing.pro.period": "/month",
    "pricing.pro.popular": "Popular",
    "pricing.pro.cta": "Upgrade to Pro",
    "pricing.pro.f1": "Everything in Free, plus:",
    "pricing.pro.f2": "See who viewed your dating profile",
    "pricing.pro.f3": "Filter matches by MBTI or Major",
    "pricing.pro.f4": "Bump marketplace listings to the top",
    "pricing.pro.f5": "1 direct \"Super Chat\" per week",
    "pricing.pro.f6": "Priority support",
    "pricing.b2b.title": "For Businesses",
    "pricing.b2b.subtitle": "Reach the most engaged student audience in Hong Kong.",
    "pricing.recruiter.title": "Recruiter Seats",
    "pricing.recruiter.desc": "Banks, Big 4, and tech firms post verified MT/Internship listings and host anonymous AMAs.",
    "pricing.recruiter.price": "From HK$5,000/mo",
    "pricing.ads.title": "Hyper-Local Ads",
    "pricing.ads.desc": "Promote your business to students at specific campuses. Pinned posts, banner placements, and more.",
    "pricing.ads.price": "Custom pricing",

    // Tech
    "tech.badge": "Technical Architecture",
    "tech.title1": "Built for",
    "tech.title2": "Scale & Safety",
    "tech.subtitle": "Enterprise-grade security and performance, designed by FinTech minds who understand that trust is everything.",
    "tech.stack.title": "Modern Stack",
    "tech.stack.desc": "Next.js (React) frontend with Node.js/PostgreSQL backend for fast, app-like performance and complex relational data.",
    "tech.ai.title": "AI Moderation",
    "tech.ai.desc": "Integrated AI moderation API from Day 1 to flag hate speech, bullying, and doxxing. Safety is non-negotiable.",
    "tech.ban.title": "The Ultimate Ban Hammer",
    "tech.ban.desc": "Severe violations result in a permanent .edu.hk hash ban. No new accounts, no second chances for bad actors.",
    "tech.infra.title": "Scalable Infrastructure",
    "tech.infra.desc": "Built to handle traffic spikes during add/drop periods and viral campus moments. Real-time chat with WebSocket support.",

    // CTA
    "cta.title1": "Ready to Join the",
    "cta.title2": "Walled Garden",
    "cta.title3": "?",
    "cta.subtitle": "UniVibe HK is launching soon. Be among the first verified students to experience the campus super-app Hong Kong has been waiting for.",
    "cta.waitlist": "Join the Community",
    "cta.business": "Contact for Business",

    // Footer
    "footer.desc": "The verified anonymous network & campus super-app for Hong Kong students.",
    "footer.product": "Product",
    "footer.company": "Company",
    "footer.legal": "Legal",
    "footer.about": "About",
    "footer.blog": "Blog",
    "footer.careers": "Careers",
    "footer.press": "Press",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.guidelines": "Community Guidelines",
    "footer.copyright": "UniVibe HK. All rights reserved.",
    "footer.tagline": "Built for Hong Kong students, by Hong Kong students.",

    // Common
    "common.coming_soon": "Feature coming soon",

    // Login page
    "login.email.title": "Join Your Campus Community",
    "login.email.subtitle": "Enter your .edu.hk email to start verification.",
    "login.email.cta": "Send Verification Code",
    "login.email.privacy_note": "We only use your email for identity verification. Your email is hashed and never publicly displayed or shared with third parties.",
    "login.verify.title": "Enter Verification Code",
    "login.verify.subtitle": "We sent a 6-digit code to",
    "login.verify.detected": "detected",
    "login.verify.cta": "Verify & Join",
    "login.verify.hint": "Code sent to your email. Valid for 10 minutes.",
    "login.success.title": "Welcome to UniVibe!",
    "login.success.subtitle": "Your identity is verified. Entering the community...",
    "login.success.redirect": "Redirecting to feed...",
    "login.error.invalid_email": "Please use a valid .edu.hk email address",
    "login.error.invalid_code": "Please enter the full 6-digit code",
    "login.toast.code_sent": "Verification code sent! Check your email.",
    "login.toast.verified": "Verified successfully!",

    // Feed page
    "feed.nav.feed": "Feed",
    "feed.nav.dating": "Dating",
    "feed.nav.tools": "Tools",
    "feed.nav.profile": "Profile",
    "feed.nav.logout": "Log Out",
    "feed.search": "Search posts...",
    "feed.cat.all": "All",
    "feed.cat.trending": "Trending",
    "feed.cat.missed": "Missed Connections",
    "feed.cat.salary": "Salary",
    "feed.compose.title": "Create a Post",
    "feed.compose.placeholder": "Share your thoughts...",
    "feed.compose.submit": "Post",
    "feed.post.success": "Post published!",
    "feed.privacy.ghost": "Ghost",
    "feed.privacy.campus": "Campus",
    "feed.privacy.major": "Major",

    // Dating page
    "dating.tab.discover": "Discover",
    "dating.tab.matches": "Matches",
    "dating.tab.profile": "My Profile",
    "dating.discover.title": "Discover Matches",
    "dating.filter": "Filter",
    "dating.filter.sexuality": "Filter by Sexuality",
    "dating.filter.all": "All",
    "dating.match": "match",
    "dating.photo_clarity": "Photo Clarity",
    "dating.messages_to_reveal": "messages to full reveal",
    "dating.messages_short": "messages",
    "dating.clarity": "clarity",
    "dating.skip": "Skip",
    "dating.vibe_check": "Vibe Check",
    "dating.vibe_sent": "Vibe Check sent! Waiting for their response 💫",
    "dating.matches.title": "Your Matches",
    "dating.matches.empty": "No matches yet. Start discovering!",
    "dating.profile.title": "Set Up Dating Profile",
    "dating.profile.sexuality": "Sexuality",
    "dating.profile.mbti": "Your MBTI",
    "dating.profile.interests": "Interests",
    "dating.profile.min": "min",
    "dating.profile.save": "Save Profile",
    "dating.profile.active": "✓ Your dating profile is active! Others can now see you.",
    "dating.error.mbti": "Please select your MBTI type",
    "dating.error.interests": "Please select at least 3 interests",
    "dating.profile_saved": "Dating profile saved!",
    "dating.discover.subtitle": "Personality first, looks later ✨",
    "dating.filter.gender": "Gender",
    "dating.filter.gender.all": "All",
    "dating.filter.gender.male": "♂ Male",
    "dating.filter.gender.female": "♀ Female",
    "dating.filter.gender.nonbinary": "⚧ Non-binary",
    "dating.filter.age": "Age",
    "dating.filter.school": "School",
    "dating.filter.faculty": "Faculty",
    "dating.filter.district": "District",
    "dating.filter.relationship": "Relationship",
    "dating.filter.religion": "Religion",
    "dating.filter.clear": "Clear all filters",
    "dating.back": "Back",
    "dating.msg_input": "Type a message...",
    "dating.msg_unlock": "messages to unlock",
    "dating.unlocked": "Unlocked",
    "dating.reveal_desc": "After matching, unlock via messages. Full reveal after 20 messages 🔓",
    "dating.no_more": "No more matches for now",
    "dating.no_more_sub": "Come back later 💫",
    "dating.how_it_works": "How Slow-Reveal Dating Works",
    "dating.how.vibe.title": "Vibe Check",
    "dating.how.vibe.desc": "Great exchange in a thread? Send a Vibe Check to start chatting",
    "dating.how.blur.title": "Blurred Photos",
    "dating.how.blur.desc": "At first you only see MBTI and major — photos are blurred",
    "dating.how.msg.title": "20 Messages",
    "dating.how.msg.desc": "Each message makes the photo a little clearer",
    "dating.how.group.title": "Group Matching",
    "dating.how.group.desc": "Match with friends for low-pressure group hangouts",
    "dating.matches.subtitle": "Keep chatting to unlock their photos 🔓",
    "dating.matches.no_matches": "No matches yet",
    "dating.matches.go_discover": "Send Vibe Checks in Discover to start matching!",
    "dating.matches.start": "Start Discovering",
    "dating.profile.subtitle": "Others will see your MBTI, interests, and blurred photo",
    "dating.profile.selected": "Selected",
    "dating.send_more": "Send",
    "dating.to_fully_unlock": "more messages to fully unlock",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("univibe-lang");
      if (saved === "en" || saved === "zh") return saved;
    }
    return "zh";
  });

  const setLang = useCallback((newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem("univibe-lang", newLang);
  }, []);

  const t = useCallback(
    (key: string) => translations[lang][key] ?? key,
    [lang]
  );

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
